config/routes.rb
Kvalitetshjulet::Application.routes.draw do

  get "user_workgroups/create"
  get "user_workgroups/destroy"
  get "active_teachers/new"
  get "active_teachers/destroy"
  get "active_principals/new"
  get "schools_users/new"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]
  get "sessions", to: "sessions#index"

  resources :active_principals
  resources :high_lights
  resources :school_users
  resources :active_teachers
  resources :events
  resources :event_types, :path => "event-types"
  get '/event-types/remove/:id', :to => 'event_types#remove', :as => :remove_event_type
  resources :schools do
    resources :schools_users
    resources :active_principals
    resources :active_teachers
    get 'add' => 'schools_users#new'
    get 'add_teacher' => 'schools#add_teacher'
    get 'add_principal' => 'schools#add_principal'
    get 'destroy_image' => 'schools#destroy_image'

    scope '/principal', :module => 'principal', :as => 'principal' do
      resources :users
    end
    scope '/teacher', :module => 'teacher', :as => 'teacher' do
      resources :users
      get 'schools' => 'users#school'
    end
  end

  resources :user_workgroups

  resources :workgroups do
    get 'add_user' => 'workgroups#add_user'
  end

  get '/users/:id', :to => 'users#show', :as => :user

  scope '/admin', :module => 'admin', :as => 'admin' do
      resources :users
  end

  scope '/juror', :module => 'juror', :as => 'juror' do
      resources :users
  end

  scope '/principal', :module => 'principal', :as => 'principal' do
      resources :users
  end

  scope '/teacher', :module => 'teacher', :as => 'teacher' do
      resources :users do
        collection { post :import }
      get 'schools' => 'users#school'
    end
  end

  get "sessions/test", to: "sessions#test"
  get "sessions/events", to: "sessions#events"
  get "sessions/show_week_events/:id/:type", to: "sessions#show_week_events"
  get "sessions/edit_week_event/:id(/:type)", to: "sessions#edit_week_event"
  get "sessions/new_week_event/:id/:type", to: "sessions#new_week_event"
  get "sessions/user/:id", to: "sessions#user"
  get "sessions/changeyear/:year", to: "sessions#set_selected_year"

  get "sessions/show_high_lights/:id", to: "sessions#show_high_lights"
  get "sessions/new_high_lights/:id", to: "sessions#new_high_lights"
  get "sessions/edit_high_lights/:id", to: "sessions#edit_high_lights"
  get "sessions/show_specific_highlights/:id", to: "sessions#show_specific_highlights"

  get "sessions/delete_file/:id", to: "sessions#delete_file"

  root 'sessions#index'










end

app/views/shared/_admin_navbar.html.erb
<!-- CURRENT USER NAME -->
  <li>
        <%= content_tag(:div, "#{session[:user_name]}", :style => "font-size:18px; line-height: 45px; color: #ededed; padding-right: 12px; margin-right: -1px;") %>
  </li>
  <li class="divider"></li>

<!-- BACK TO WHEEL -->
  <li>
    <div>
      <%= link_to 'Hjulet', root_url, :style => "padding-top: 7px; padding-bottom: 7px; font-size:18px; line-height: 45px;"%>
    </div>
  </li>
  <li class="divider"></li>

<!-- HELP -->
  <li>
    <div style="font-size:30px; line-height: 45px;">
        <a data-reveal-id="myModal" style="color: #ededed; padding-left: 15px; padding-right: 16px;" data-reveal><strong>?</strong></a>
      <%= render "shared/tutorial" %>
    </div>
  </li>
  <li class="divider"></li>

<!-- PRINT -->
  <% if (current_uri = request.env['PATH_INFO']== "/") %>
  <li>
    <div style="font-size:30px; line-height: 45px;">
        <a onclick="prepareprint();" style="color: #ededed; padding-left: 15px; padding-right: 16px;">
          <i class="step fi-print size-72"></i>
        </a>
    </div>
  </li>
  <li class="divider"></li>        
  <% else %>
        
  <% end %>

<!-- ADMINISTRATION -->
  <li class="has-dropdown">
    <div style="font-size:30px; line-height: 45px;">
        <a style="color: #ededed; padding-left: 15px; padding-right: 16px;">
          <i class="step fi-widget size-72"></i>
        </a>
    </div>
    <ul class="dropdown">
      <li><%= link_to 'Administratörer', admin_users_path %></li>
      <li><div class="insethax"></div><%= link_to 'Skolor', schools_path %></li>
      <!-- <li><%= link_to 'Nämndemän', juror_users_path %></li> --> <!-- utkommenterat för eventuell framtida utveckling -->
      <li><%= link_to 'Rektorer', principal_users_path %></li>
      <li><%= link_to 'Personal', teacher_users_path %></li>
      <li><%= link_to 'Aktivitetstyper', event_types_path %></li>
    </ul>
  </li>
  <li class="divider"></li>

<!-- PROFILE -->
  <li class="has-dropdown">
    <div style="font-size:30px; line-height: 45px;">
      <a style="color: #ededed; padding-left: 17px; padding-right: 20px;">
        <i class="step fi-torso size-72"></i>
      </a>
    </div>
    <ul class="dropdown" style="margin-right:8px;">
      <!-- GET USER ID FROM SESSION -->
      <li><div class="insethax" style="width: 126px; "></div>
        <%= link_to 'Min profil', admin_user_path(current_user) %>
      </li>
      <!-- DESTROY SESSION -->
      <li><%= link_to 'Logga ut', signout_path %></li>
    </ul>
  </li>

  

app/views/shared/_juror_navbar.html.erb
<!-- CURRENT USER NAME -->
  <li class="active" style="height: 45px;">
    <div style="font-size:18px; line-height: 45px; color: #ededed;">
      <div class="separator" style="padding-right: 12px; margin-right: -1px;"><%= session[:user_name] %>
      </div>
    </div>
  </li>

<!-- BACK TO WHEEL -->
  <li class="active" style="height: 45px;">
    <div style="font-size:18px; line-height: 45px;">
      <div class="separator"><%= link_to 'Hjulet', root_url, :style => "padding-top: 7px; padding-bottom: 7px;"%>
      </div>
    </div>
  </li>

<!-- HELP -->
  <li class="active" style="height: 45px;">
    <div style="font-size:30px; line-height: 45px;">
      <div class="separator">
        <a data-reveal-id="myModal" style="color: #ededed; padding-left: 15px; padding-right: 16px;" data-reveal><strong>?</strong></a>
      </div>
      <%= render "shared/tutorial" %>
    </div>
  </li>

<!-- PRINT -->
  <li class="active" style="height: 45px;">
    <div style="font-size:30px; line-height: 45px;">
      <div class="separator">
        <a onclick="window.print();return false;" style="color: #ededed; padding-left: 15px; padding-right: 16px;">
          <i class="step fi-print size-72"></i>
        </a>
      </div>
    </div>
  </li>

<!-- PROFILE -->
  <li class="has-dropdown">
    <div style="font-size:30px; line-height: 45px;  margin-right: 5px;">
      <div class="separator">
        <a style="color: #ededed; padding-left: 15px; padding-right: 15px;">
          <i class="step fi-torso size-72"></i>
        </a>
      </div>
    </div>
    <ul class="dropdown" style="margin-right:8px;">
      <!-- GET USER ID FROM SESSION -->
      <li>
        <div class="insethax" style="width: 126px;">
        </div>
        <%= link_to 'Min profil', "/juror/users/#{session[:user_id]}/edit" %>
      </li>
      <!-- DESTROY SESSION -->
      <li><%= link_to 'Logga ut', signout_path %></li>
    </ul>
  </li>

app/views/shared/_principal_navbar.html.erb
<!-- CURRENT USER NAME -->
  <li>
        <%= content_tag(:div, "#{session[:user_name]}", :style => "font-size:18px; line-height: 45px; color: #ededed; padding-right: 12px; margin-right: -1px;") %>
  </li>
  <li class="divider"></li>

<!-- BACK TO WHEEL -->
  <li>
    <div>
      <%= link_to 'Hjulet', root_url, :style => "padding-top: 7px; padding-bottom: 7px; font-size:18px; line-height: 45px;"%>
    </div>
  </li>
  <li class="divider"></li>

<!-- HELP -->
  <li>
    <div style="font-size:30px; line-height: 45px;">
        <a data-reveal-id="myModal" style="color: #ededed; padding-left: 15px; padding-right: 16px;" data-reveal><strong>?</strong></a>
      <%= render "shared/tutorial" %>
    </div>
  </li>
  <li class="divider"></li>

<!-- PRINT -->
  <% if (current_uri = request.env['PATH_INFO']== "/") %>
  <li>
    <div style="font-size:30px; line-height: 45px;">
        <a onclick="prepareprint();" style="color: #ededed; padding-left: 15px; padding-right: 16px;">
          <i class="step fi-print size-72"></i>
        </a>
    </div>
  </li>
  <li class="divider"></li>        
  <% else %>
        
  <% end %>

<!-- ADMINISTRATION -->
  <li class="has-dropdown">
    <div style="font-size:30px; line-height: 45px;">
        <a style="color: #ededed; padding-left: 15px; padding-right: 16px;">
          <i class="step fi-widget size-72"></i>
        </a>
    </div>
    <ul class="dropdown" style="height: 45px;">
      <li><div class="insethax"></div><%= link_to 'Skolor', schools_path %></li>
      <li><%= link_to 'Rektorer', principal_users_path %></li>
      <li><%= link_to 'Arbetsgrupper', workgroups_path %></li>
      <li><%= link_to 'Personal', teacher_users_path %></li>
    </ul>
  </li>
  <li class="divider"></li>

<!-- PROFILE -->
  <li class="has-dropdown">
    <div style="font-size:30px; line-height: 45px;">
        <a style="color: #ededed; padding-left: 17px; padding-right: 20px;">
          <i class="step fi-torso size-72"></i>
        </a>
    </div>
    <ul class="dropdown" style="margin-right:8px;">
      <!-- GET USER ID FROM SESSION -->
      <li><div class="insethax" style="width: 126px;"></div>
        <%= link_to 'Min profil', principal_user_path(current_user) %>
      </li>
      <!-- DESTROY SESSION -->
      <li><%= link_to 'Logga ut', signout_path %></li>
    </ul>
  </li>

app/views/shared/_teacher_navbar.html.erb
<!-- CURRENT USER NAME -->
  <li>
        <%= content_tag(:div, "#{session[:user_name]}", :style => "font-size:18px; line-height: 45px; color: #ededed; padding-right: 12px; margin-right: -1px;") %>
  </li>
  <li class="divider"></li>

<!-- BACK TO WHEEL -->
  <li>
    <div>
      <%= link_to 'Hjulet', root_url, :style => "padding-top: 7px; padding-bottom: 7px; font-size:18px; line-height: 45px;"%>
    </div>
  </li>
  <li class="divider"></li>

<!-- HELP -->
  <li>
    <div style="font-size:30px; line-height: 45px;">
        <a data-reveal-id="myModal" style="color: #ededed; padding-left: 15px; padding-right: 16px;" data-reveal><strong>?</strong></a>
      <%= render "shared/tutorial" %>
    </div>
  </li>
  <li class="divider"></li>

<!-- PRINT -->
  <% if (current_uri = request.env['PATH_INFO']== "/") %>
  <li>
    <div style="font-size:30px; line-height: 45px;">
        <a onclick="prepareprint();" style="color: #ededed; padding-left: 15px; padding-right: 16px;">
          <i class="step fi-print size-72"></i>
        </a>
    </div>
  </li>
  <li class="divider"></li>        
  <% else %>
        
  <% end %>

<!-- PROFILE -->
  <li class="has-dropdown">
    <div style="font-size:30px; line-height: 45px;">
        <a style="color: #ededed; padding-left: 17px; padding-right: 20px;">
          <i class="step fi-torso size-72"></i>
        </a>
    </div>
    <ul class="dropdown" style="margin-right:8px;">
      <!-- GET USER ID FROM SESSION -->
      <li>
        <div class="insethax" style="width: 126px;">
        </div>
        <%= link_to 'Min profil', teacher_user_path(current_user) %>
      </li>
      <!-- DESTROY SESSION -->
      <li><%= link_to 'Logga ut', signout_path %></li>
    </ul>
  </li>

app/views/shared/_tutorial.html.erb
<div id="myModal" class="reveal-modal" style="padding: 40px;" data-reveal>
  <h4 class="large-12 columns">Hjälp | <%= session[:user_type] %></h4>
  <div class="large-7 columns">
    <p class="tutorial_highlight_green" style="margin: 0px; padding-bottom: 12px;"><b>Utbildningsnämnden</b><br/>
    Den yttersta ringen är utbildningsnämndens årshjul.</p>
    <p class="tutorial_highlight_blue" style="margin: 0px; padding-bottom: 12px;"><b>Utbildningsförvaltningen</b><br/>
    Den näst yttersta ringen beskriver hur det förvaltningsövergripande kvalitetsarbetet är organiserat. I detta årshjul finns uppföljningsdatum för de övergripande kvalitetsområdena samt information om aktuella kvalitetsmått.</p>
    <p class="tutorial_highlight_teal" style="margin: 0px; padding-bottom: 12px;"><b>Skola</b><br/>
    Den näst innersta ringen beskriver hur din skola valt att organisera det systematiska kvalitetsarbetet. Rektor på skolan beslutar om hur och när de övergripande kvalitetsområdena planeras, genomförs, följs upp och analyseras.</p>
    <p class="tutorial_highlight_purple" style="margin: 0px; padding-bottom: 12px;"><b>Personal</b><br/>
    Den innersta ringen är ett planeringsverktyg för dig som anställd. Genom att markera skiftningar i arbetsbelastningen synliggörs ditt årshjul. Detta kan t.ex. fungera som ett underlag till RUS-samtalet. Här kan du också beskriva med hjälp av kommentarer hur du arbetar med din skolas kvalitetsarbete.</p>
  </div>
  <div class="large-5 columns" style="height: 320px;">
    <%= image_tag("none_highlighted.jpg", :alt => "none_highlighteded", :class => "none_highlighteded", :style => 'height: 350px; width: 350px; position: absolute; float: left; margin-left: 60px; z-index: 1;') %>
    <%= image_tag("first_highlighted.jpg", :alt => "first_highlighted", :class => "first_highlighted", :style => 'height: 350px; width: 350px; position: absolute; float: left; margin-left: 60px; z-index: 2; opacity: 0;') %>
    <%= image_tag("second_highlighted.jpg", :alt => "second_highlighted", :class => "second_highlighted", :style => 'height: 350px; width: 350px; position: absolute; float: left; margin-left: 60px; z-index: 2; opacity: 0;') %>
    <%= image_tag("third_highlighted.jpg", :alt => "third_highlighted", :class => "third_highlighted", :style => 'height: 350px; width: 350px; position: absolute; float: left; margin-left: 60px; z-index: 2; opacity: 0;') %>
    <%= image_tag("fourth_highlighted.jpg", :alt => "fourth_highlighted", :class => "fourth_highlighted", :style => 'height: 350px; width: 350px; position: absolute; float: left; margin-left: 60px; z-index: 2; opacity: 0;') %>
  </div>

  <div class="large-12 columns">
    <h4>Lägga till event</h4>
  </div>

  <div class="large-5 columns">
    <%= image_tag("belastning_form.jpg", :alt => "belastning_form.jpg") %>
  </div>
  <div class="large-7 columns">
  <p><br>För att lägga till en händelse klickar du på den vecka, på ditt hjul, där du vill lägga det.
  Det kommer då fram ett formulär som du fyller i med din information (se bild). Titel, kommentar, datum, färg, och eventuella filer.<br> Tryck sedan på "Skapa" för att spara informationen. <br>
  Du kommer då se en prick med din valda färg på veckan som representerar händelsen. 
  <br>Du kan endast skapa händelser på din egen cirkel.
  En vecka med fler händelser kommer ha en "delad" cirkel med olika färger.</p>
  
  </div> 

  <div class="large-12 columns">
    <h4>Lägga till belastning</h4>
  </div>

  <div class="large-7 columns">
  <p><br>För att lägga till belastning klickar du på veckan i ditt hjul där belastningen ska ligga. Du fyller i formuläret som dyker upp med information; aktivitet, samt belastning. Antingen hög, normal eller låg. Klicka på "Lägg till" så sparas informationen.</p>
  </div>

  <div class="large-5 columns">
    <%= image_tag("belastning_form.jpg", :alt => "belastning_form.jpg") %>
  </div>

  
  <a class="close-reveal-modal">&#215;</a>
</div>