config/routes.rb
Kvalitetshjulet::Application.routes.draw do

  get "user_workgroups/create"
  get "user_workgroups/destroy"
  get "active_teachers/new"
  get "active_teachers/destroy"
  get "active_principals/new"
  get "schools_users/new"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]
  get "sessions", to: "sessions#index"

  resources :active_principals
  resources :high_lights
  resources :school_users
  resources :active_teachers
  resources :events
  resources :event_types, :path => "event-types"
  get '/event-types/remove/:id', :to => 'event_types#remove', :as => :remove_event_type
  resources :schools do
    resources :schools_users
    resources :active_principals
    resources :active_teachers
    get 'add' => 'schools_users#new'
    get 'add_teacher' => 'schools#add_teacher'
    get 'add_principal' => 'schools#add_principal'
    get 'destroy_image' => 'schools#destroy_image'

    scope '/principal', :module => 'principal', :as => 'principal' do
      resources :users
    end
    scope '/teacher', :module => 'teacher', :as => 'teacher' do
      resources :users
      get 'schools' => 'users#school'
    end
  end

  resources :user_workgroups

  resources :workgroups do
    get 'add_user' => 'workgroups#add_user'
  end

  get '/users/:id', :to => 'users#show', :as => :user

  scope '/admin', :module => 'admin', :as => 'admin' do
      resources :users
  end

  scope '/juror', :module => 'juror', :as => 'juror' do
      resources :users
  end

  scope '/principal', :module => 'principal', :as => 'principal' do
      resources :users
  end

  scope '/teacher', :module => 'teacher', :as => 'teacher' do
      resources :users do
        collection { post :import }
      get 'schools' => 'users#school'
    end
  end

  get "sessions/test", to: "sessions#test"
  get "sessions/events", to: "sessions#events"
  get "sessions/show_week_events/:id/:type", to: "sessions#show_week_events"
  get "sessions/edit_week_event/:id(/:type)", to: "sessions#edit_week_event"
  get "sessions/new_week_event/:id/:type", to: "sessions#new_week_event"
  get "sessions/user/:id", to: "sessions#user"
  get "sessions/changeyear/:year", to: "sessions#set_selected_year"

  get "sessions/show_high_lights/:id", to: "sessions#show_high_lights"
  get "sessions/new_high_lights/:id", to: "sessions#new_high_lights"
  get "sessions/edit_high_lights/:id", to: "sessions#edit_high_lights"
  get "sessions/show_specific_highlights/:id", to: "sessions#show_specific_highlights"

  get "sessions/delete_file/:id", to: "sessions#delete_file"

  root 'sessions#index'










end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user_or_school, polymorphic: true
  has_one :event_workgroup
  belongs_to :event_type, :foreign_key => 'type_id'
  has_one :workgroup, through: :event_workgroup
  validates :week, :title, :datetime, :type_id, presence: true
  validates :week, numericality: {greater_than_or_equal_to: 0}
  validates :week, numericality: {less_than_or_equal_to: 51}
  mount_uploader :file, FileUploader
  validates_integrity_of  :file
  validates_processing_of :file

  def self.by_year(year)
    where("strftime('%Y', created_at) = ?", year)
  end

  # default_scope where("strftime('%Y', created_at) = ?", 2014)
end


#--> Review by Niklas 10:44 11/3-14

app/models/event_type.rb
class EventType < ActiveRecord::Base
    validates :name, :color, :presence => true
    has_many :events, :foreign_key => 'type_id'
    after_destroy :ensure_one_type_remains

    private
        def ensure_one_type_remains
            if EventType.count.zero?
                raise "Det måste alltid finnas minst en aktivitetstyp"
            end
        end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :auth #authenticate
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.by_year(session[:year_selected]).all

  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new 
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json

  def create
    new_params = event_params
    if new_params.has_key?(:workgroup)
      new_params.delete(:workgroup)
    end
    @event = Event.new(new_params)
    @event.dot_color = @event.event_type.color;
    respond_to do |format|
      if @event.save
        @adminOnJuror = ''
        if @event.user_id.present? and @event.school_id.present? and current_user.user_type == 'admin'
          @adminOnJuror = 'juror';
        end
        @events = Event.where('id' => @event.id)
        if @event.user_id?
          @owner = User.find(@event.user_id)
        else
          @owner = School.find(@event.school_id)
        end
        if event_params.has_key?(:workgroup) 
          EventWorkgroup.create(event_id: @event.id, workgroup_id: event_params.require(:workgroup))
        end
        format.html { redirect_to @event, notice: 'Händelsen har skapats!' }
        format.json { render action: 'show', status: :created, location: @event }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
    Rails.logger.info(@event.errors.inspect) 
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    # @events = Event.find(params[:id])
    if @event.user_id.present?
      @user = User.find(@event.user_id)
    else
      @user = current_user
    end
    @pre_color = @event.event_type.present? ? @event.event_type.color : @event.dot_color

    new_params = event_params
    if new_params.has_key?(:workgroup)
      new_params.delete(:workgroup)
    end
    
    @old_title = @event.title
    
    new_params[:dot_color] = EventType.find(new_params[:type_id]).color;

    respond_to do |format|
      if @event.update(new_params)
        @adminOnJuror = ''
        if @event.user_id.present? and @event.school_id.present? and current_user.user_type == 'admin'
          @adminOnJuror = 'juror';
        end
        if @event.user_id?
          @owner = User.find(@event.user_id)
        else
          @owner = School.find(@event.school_id)
        end
        if event_params.has_key?(:workgroup)
          @event.event_workgroup.update(workgroup: Workgroup.find(event_params[:workgroup]));
        end
        format.html { redirect_to @event, notice: 'Händelsen har uppdaterats!' }
        format.json { head :no_content } 
        format.js 
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    output = @event.to_json
    @color = @event.event_type.present? ? @event.event_type.color : @event.dot_color
    @ringName = (@event.school_id.present? and @event.user_id.present?) ? 'juror' : ''
    p @ringName
    p @ringName
    p @ringName
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Händelsen har tagits bort!' }
      format.json { render :json => output }
      format.js
    end

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
     @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :comment, :datetime, :user_id, :school_id, :week, :file, :type_id, :ring_name, :workgroup)
  end

  # checks your permissions
  def auth
    if session[:user_id] == nil
       redirect_to root_url, notice: "Du måste logga in med ditt google konto för att använda applikationen!"
    end
  end
end


#--> Review by Niklas 10:30 27/3-14

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event, :html => {:multipart => true}) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "fel") %> hindrar denna användaren från att sparas:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titel %><br>
    <%= f.text_field :title, :required => true %>
  </div>
  <div class="field">
    <%= f.label :kommentar %><br>
    <%= f.text_area :comment, :required => true %>
  </div>
  <div class="field">
    <%= f.label :datum %><br>
    <%= f.datetime_select :datetime, :required => true %>
  </div>
  <div class="field">
    <%= f.label :roll %><br>
    <%= f.text_field :user_id, :required => true %>
  </div>
  <div class="field">
    <%= f.label :skola %><br>
    <%= f.text_field :school_id, :required => true %>
  </div>
   <div class="field">
    <%= f.label :vecka %><br>
    <%= f.text_field :week, :required => true %>
  </div>
  <div class="field">
    <%= f.label :fil %><br>
    <%= f.file_field :file, :required => true %>
  </div>
  <% 
    ##
    # The colorpicker is written in JavaScript in assets/javascript/syronex-colorpicker.js
    # with css-styles in assets/stylesheets/events.css.scss 
    ##
  %>

  <div class="actions" style="float: left; margin-right: 10px;">
    <% if params[:action] == 'new' %>
      <%= f.submit "Lägg till", :class => "button tiny", style: 'margin-top: 10px' %>
    <% else %>
      <%= f.submit "Uppdatera", :class => "button tiny", style: 'margin-top: 10px;' %>
    <% end %>
  </div>
<% end %>


app/views/events/_no_events.html.erb
<h3>Vecka <%= @week.to_i+1 %></h3>
<hr>

<div class='content'>
  <b>Det verkar inte finnas några aktiviteter här.</b>
</div>


app/views/events/_show.html.erb
<h3>Vecka <%= @week.to_i+1 %></h3>
<hr>
<% can_add_event = false %>
<% @events.each do |event| %>
    <div class='content'>
        <b><%= event.title %></b><div class="event_color" style="background-color:<%= event.event_type.present? ? event.event_type.color : event.dot_color %>;"></div>
        <%= if event.workgroup.present?; tag(:br) + "Arbetsgrupp: #{event.workgroup.name}" end %>
        <br/>
        <i><%= l event.datetime, format: :short %></i><br/><br/>
        <%= simple_format(auto_link(event.comment)) %><br/>

        <% if event.file.present? %>
            Bifogad fil: <%= link_to 'ladda ner' ,event.file.url %>
            <br/>
        <% end %>
        <br/>

        <% # Sets so that only a user with the same usertype or has the same school can see the edit- and remove- buttons  %>
        <% isPrincipal = (event.school_id.present? and current_user.schools.map{|a| a.id}.include? event.school_id and current_user.user_type == 'principal') %>
        <% isTeacher = (event.user_id.present? and current_user.id == event.user_id and current_user.user_type == 'teacher') %>
        <% if isPrincipal or isTeacher or (event.user_id.present? and @usersWithSameUsertypeAsCurrentUser.map{|a| a.id}.include? event.user_id and current_user.user_type == "admin") %>
          <%= button_tag 'Redigera', :data => { editevent: "sessions/edit_week_event/#{event.id}" }, :class => 'unbind_click button tiny', style: 'margin-right: 5px;' %>
          <%= link_to 'Ta bort', event_path(event.id), method: :delete, remote: true, :class => 'button tiny back', onclick: 'deleteEvent(this);' %>
          <% can_add_event = true; %>
        <% end %>
    </div>
<% end %>
<hr/>
<% if can_add_event %>
    <% side_to_load = "sessions/new_week_event/#{@week}/#{@events[0].ring_name}" %>
    <%= button_tag 'Lägg till event', :data=> { editevent: side_to_load }, :class => 'button tiny', style: 'margin-top: 10px;' %>
<% end %>

app/views/events/_wheel_form.html.erb

<% if (current_user.user_type == "admin") or 
  (current_user.user_type == "juror") or 
  (
    (current_user.user_type == "principal" or (current_user.user_type == "teacher" and !current_user.workgroups.empty?)) and current_user.schools.exists?
  ) %>
<h3>Vecka <%= @week.to_i+1 %></h3>
<hr>
<%= form_for(@event, :html => {:multipart => true}, :remote => true) do |f| %>
    <% if @event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@event.errors.count, "fel") %> hindrar aktiviteten från att sparas:</h2>

          <ul>
            <% @event.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="field">
      <%= f.label :titel %><br>
      <%= f.text_field :title, :required => true %>
    </div>
    <div class="field">
      <%= f.label :kommentar %><br>
      <%= f.text_area :comment, :required => true %>
    </div>
    <div class="field">
      <%= f.label :datum %><br>
      <% if @event.datetime.present?  %>
        <% if @event.week.present?  %>
          <%= f.text_field :datetime, :value => @event.datetime.to_date, :data => {week: @event.week}, :required => true %>
        <% else %>
          <%= f.text_field :datetime, :value => @event.datetime.to_date, :data => {week: params[:id]}, :required => true %>
        <% end %>
      <% else %>
         <% if @event.week.present?  %>
          <%= f.text_field :datetime, :data => {week: @event.week}, :required => true %>
        <% else %>
          <%= f.text_field :datetime, :data => {week: params[:id]}, :required => true %>
        <% end %>
      <% end %>
    </div>

    <div id="dot_color" class="field">
      <%= f.label :type_id, 'Välj typ av aktivitet' %>
      <%= f.hidden_field :type_id %>
    </div>
    <%= f.hidden_field :type_id, :id => 'pre_color', :name => 'pre_color', :value => @pre_color %>
    <div id="output"></div>

    <div class="field">

      <% if current_user.user_type == 'admin' %>
          <% if @current_ring == 'juror' %>
              <% # När både user_id och school_id är satt så är det ett juror-event %>
              <%= f.hidden_field :school_id, :value => 0 %>
              <%= f.hidden_field :user_id, :value => current_user.id %>
          <% else %>
              <%= f.hidden_field :user_id, :value => current_user.id %>
              <% # en hidden field med ett "nil" värde som gör det synligt för alla skolor %>
              <%= f.hidden_field :school_id, :value => "" %>
          <% end %>

      <% elsif @current_ring == 'principal' %>
          <!-- hämta alla skolor som current user är registrerad på -->
          <%= f.label :skola %><br>
          <%= f.collection_select(:school_id, current_user.schools, :id, :name) %>
          <%= f.hidden_field :user_id, :value => "" %>

      <% elsif @current_ring == 'teacher' %>

          <%= f.label :workgroup, 'Arbetsgrupp' %><br>
          <%= f.collection_select(:workgroup, current_user.workgroups, :id, :name) %>

          <%= f.hidden_field :school_id, :value => @schoolId %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
      <% end %>
    </div>
    <div class="field">
      <% if @event.week.present? %>
            <%= f.hidden_field :week %>
      <% else %>
            <%= f.hidden_field :week, :value => params[:id] %>
      <% end %>
    </div>

    <div class="field">
      <%= f.label :file, 'Fil' %><br>
      <%= f.file_field :file %>
    </div>
    <%= f.hidden_field :ring_name, :value => @current_ring %>

    <div class="actions">
      <% if @event.datetime.present?  %>
        <% submit_text = 'Uppdatera aktivitet' %>
      <% else %>
        <% submit_text = 'Skapa aktivitet' %>
      <% end %>
      <%= f.submit submit_text ,:class => 'button tiny', :remote => true, style: 'float: left; margin-right: 10px;' %>
    </div>
    <button class="actions button tiny" style="background-color: #ba0000; margin-left:10px;" type="button" onclick="toggle();">Avbryt</button>
<% end %>
  <div id = "delete_file" >
      <% if @event.file.present? %>
            Bifogad fil: <%= link_to 'ladda ner', @event.file.url %>
            | <%= button_tag 'Ta bort', :data => { deletefile: "/sessions/delete_file/#{@event.id}" }, :class => 'unbind_click, button tiny back' %>
      <% end %>

    </div>

<script>
    $(document).ready(function(){
        $('#event_comment').autosize();
    });

</script>

<% else %>
<h4 class="subheader">Du kan inte skapa aktiviteter när du inte tillhör någon skola eller arbetsgrupp. Be administratören att lägga till dig till en skola eller arbetsgrupp.</h4>
<% end %>

app/views/events/create.js.erb
$('#new_event').bind('ajax:complete', function(resp) {
	$("#notify").html("Händelsen har skapats.")
                .fadeIn("slow");
    setTimeout( function() { $("#notify").fadeOut("slow"); }, 5000);

    var type,
        ringName = '<%= @event.ring_name %>',
        eventColor = '<%= @event.event_type.color %>',
        eventTitle = '<%= @event.title %>',
        week = parseInt(<%= @event.week %>);

    <% if @adminOnJuror == 'juror' %>
        type = 'juror';
    <% elsif @owner.attributes.has_key?('user_type')  %>
        type = '<%= @owner.user_type %>';
    <% else %>
        type = '<%= @owner.id %>';
    <% end %>
    loadSideWithAjax('sessions/show_week_events/'+week+'/'+type);
    
    $('.eventMarker').each(function() {
        $this = $(this);
        if ($this.css("background-color") == 'rgb(255, 255, 255)') {
            $this.click();
        }
    });

    wheel.createEvent({
        ringName: ringName,
        week: week,
        events: [{
            color: eventColor,
            title: eventTitle
        }]
    }).redrawRing(ringName);
});


app/views/events/destroy.js.erb
var ringName = '<%= @ringName %>',
    week = parseInt('<%= @event.week %>'),
    color = '<%= @color %>',
    eventTitle = '<%= @event.title %>';

var ring = ringName === 'juror' ? ringName : gon.c_user_type;

wheel.destroyEvent(ring, week, color, eventTitle)
    .redrawRing(ring);

app/views/events/edit.html.erb
<h1>Redigera event</h1>

<%= render 'form' %>

<%= link_to 'Tillbaka', events_path, class: 'button tiny back', style: 'color: white; margin-top: 20px;'  %>

app/views/events/index.html.erb
<h1>Lista över event</h1>

<table>
  <thead>
    <tr>
      <th>Titel</th>
      <th>kommentar</th>
      <th>Datum</th>
      <th>Vecka</th>
      <th>Roll</th>
      <th>Skola</th>
      <th>Bifogad Fil</th>
      <th class="list">Visa</th>
      <th class="list">Redigera</th>
      <th class="list">Ta bort</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.comment %></td>
        <td><%= event.datetime %></td>
        <td><%= event.week %></td>
        <td><%= event.user_id %></td>
        <td><%= event.school_id %></td>
        <% if event.file.present? %>
        <td><%= link_to 'Ladda ner', event.file.url %></td>
        <% else %>
        <td><span style="color:lightgrey;">Ingen fil</span></td> 
        <% end %>
        <td><%= link_to 'Visa', event %></td>
        <td><%= link_to 'Redigera', edit_event_path(event) %></td>
        <td><%= link_to 'Ta bort', event, method: :delete, data: { confirm: "Är du säker på att du vill ta bort #{event.title} ?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Lägg till', new_event_path, class: 'button tiny', style: 'color: white; margin-top: 20px;' %>

app/views/events/new.html.erb
<h1>Lägg till event</h1>

<%= render 'form' %>

<%= link_to 'Tillbaka', principal_users_path, class: 'button tiny back', style: 'color: white; margin-top: 20px;'  %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titel:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Kommentar:</strong>
  <%= @event.comment %>
</p>

<p>
  <strong>Datum:</strong>
  <%= @event.datetime %>
</p>

<p>
  <strong>Vecka:</strong>
  <%= @event.week %>
</p>

<p>
  <strong>Roll:</strong>
  <%= @event.user_id %>
</p>

<p>
  <strong>Skola:</strong>
  <%= @event.school_id %>
</p>

<% if @event.file.present? %>
<p>
  <strong>Bifogad fil:</strong>
<%= link_to 'Ladda ner', @event.file.url %>
</p>

<% else %>
<p>
  <strong>Bifogad fil:</strong>
<span style="color:lightgrey;">Ingen fil</span>
</p>

<% end %>





<%= link_to 'Redigera', edit_event_path(@event), class: 'button tiny', style: 'color: white; margin-top: 20px;'  %> |
<%= link_to 'Tillbaka', events_path, class: 'button tiny back', style: 'color: white; margin-top: 20px;'  %>

app/views/events/update.js.erb
$('.edit_event').unbind('ajax:complete').bind('ajax:complete', function(resp) {
	$("#notify").html("Händelsen har uppdaterats.");
    $("#notify").fadeIn("slow");
    setTimeout(function(){$("#notify").fadeOut("slow");},5000);
    var usertype = '<%= @user.user_type %>';
    var week = $($(resp.target)[0]).find("#event_week")[0].value;
    edit_week = parseInt('<%= @event.week %>');
    var type;
    <% if @adminOnJuror == 'juror' %>
        type = 'juror';
    <% elsif @owner.attributes.has_key?('user_type')  %>
        type = '<%= @owner.user_type %>';
    <% else %>
        type = '<%= @owner.id %>';
    <% end %>
    loadSideWithAjax('sessions/show_week_events/'+week+'/'+type);
    // <% if current_user.user_type == 'admin' &&  @adminOnJuror == 'juror' %>
    //     var ringname = 'juror';
    // <% else %>
    //     var ringname = '<%= current_user.user_type %>';
    // <% end  %>

    var ringName = '<%= @event.ring_name %>',
        fromColor = '<%= @pre_color %>',
        toColor = '<%= @event.event_type.color %>',
        fromTitle = '<%= @old_title %>',
        toTitle = '<%= @event.title %>';

    wheel.getWedge(ringName, edit_week)
        .update({
            from: {
                color: fromColor,
                title: fromTitle
            },
            to: {
                color: toColor,
                title: toTitle
            }
        });
    wheel.redrawRing(ringName);
});