config/routes.rb
Kvalitetshjulet::Application.routes.draw do

  get "user_workgroups/create"
  get "user_workgroups/destroy"
  get "active_teachers/new"
  get "active_teachers/destroy"
  get "active_principals/new"
  get "schools_users/new"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]
  get "sessions", to: "sessions#index"

  resources :active_principals
  resources :high_lights
  resources :school_users
  resources :active_teachers
  resources :events
  resources :event_types, :path => "event-types"
  get '/event-types/remove/:id', :to => 'event_types#remove', :as => :remove_event_type
  resources :schools do
    resources :schools_users
    resources :active_principals
    resources :active_teachers
    get 'add' => 'schools_users#new'
    get 'add_teacher' => 'schools#add_teacher'
    get 'add_principal' => 'schools#add_principal'
    get 'destroy_image' => 'schools#destroy_image'

    scope '/principal', :module => 'principal', :as => 'principal' do
      resources :users
    end
    scope '/teacher', :module => 'teacher', :as => 'teacher' do
      resources :users
      get 'schools' => 'users#school'
    end
  end

  resources :user_workgroups

  resources :workgroups do
    get 'add_user' => 'workgroups#add_user'
  end

  get '/users/:id', :to => 'users#show', :as => :user

  scope '/admin', :module => 'admin', :as => 'admin' do
      resources :users
  end

  scope '/juror', :module => 'juror', :as => 'juror' do
      resources :users
  end

  scope '/principal', :module => 'principal', :as => 'principal' do
      resources :users
  end

  scope '/teacher', :module => 'teacher', :as => 'teacher' do
      resources :users do
        collection { post :import }
      get 'schools' => 'users#school'
    end
  end

  get "sessions/test", to: "sessions#test"
  get "sessions/events", to: "sessions#events"
  get "sessions/show_week_events/:id/:type", to: "sessions#show_week_events"
  get "sessions/edit_week_event/:id(/:type)", to: "sessions#edit_week_event"
  get "sessions/new_week_event/:id/:type", to: "sessions#new_week_event"
  get "sessions/user/:id", to: "sessions#user"
  get "sessions/changeyear/:year", to: "sessions#set_selected_year"

  get "sessions/show_high_lights/:id", to: "sessions#show_high_lights"
  get "sessions/new_high_lights/:id", to: "sessions#new_high_lights"
  get "sessions/edit_high_lights/:id", to: "sessions#edit_high_lights"
  get "sessions/show_specific_highlights/:id", to: "sessions#show_specific_highlights"

  get "sessions/delete_file/:id", to: "sessions#delete_file"

  root 'sessions#index'










end

app/models/school.rb
class School < ActiveRecord::Base
  validates :name, presence: true
  has_many :school_users
  has_many :workgroups
  has_many :events, as: :user_or_school
  has_many :users, through: :school_users
  mount_uploader :file, CenterImageUploader
  validates_integrity_of  :file
  validates_processing_of :file
end


app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :auth
  before_action :set_school, only: [:show, :edit, :update, :destroy]


  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all

  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @principals = User.where(:user_type => "principal")
    @teachers = User.where(:user_type => "teacher")
    @activePrincipals = SchoolUser.all
    @activeTeachers = SchoolUser.all

  end

  # GET /schools/new
  def new

    if current_user.user_type == "admin"
      @school = School.new
    else
      render :text => "Du har inte behörighet att visa sidan!"
    end

  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)
    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'Skolan har skapats!' }
        format.json { render action: 'show', status: :created, location: @school }
      else
        format.html { render action: 'new' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'Skolan har uppdaterats!' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_teacher
    @school = School.find(params[:school_id])
    @teachers = User.where(:user_type=>"teacher")
    @hideTeacher = Array.new
    @showTeacher = Array.new
  end

  def add_principal
    @school = School.find(params[:school_id])
    @users = User.where(:user_type=>"principal")
    @hidePrincipal = Array.new
    @showPrincipal = Array.new
  end

  def add
    respond_to do |format|
      format.html { redirect_to(:back)}
      format.json { head :no_content }
    end
  end


  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    School.find(params[:id]).destroy 
    @asset_id = params[:id]
    #@user.destroy
    respond_to do |format|
      format.html { redirect_to schools_path, notice: "Skolan har tagits bort!" } 
      format.js 
    end
    # destroy funktionen utan ajax
    # @school.destroy
    # respond_to do |format|
    #   format.html { redirect_to schools_url }
    #   format.json { head :no_content }
    # end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_school
    @school = School.find(params[:id])
  end


  #Require params for schools.
  def school_params
    params.require(:school).permit(:name, :district, :file, :remove_file)
  end

  #Checks your permissions.
  def auth
    if session[:user_id] != nil
    else
      redirect_to root_url, notice: "Du måste logga in med ditt google konto för att använda applikationen!"
    end
  end

end

#--> Review by Niklas 10:30 27/3-14

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_addPrincipalForm.html.erb
<%= form_for SchoolUser.new do |f| %>
    <%= f.hidden_field(:school_id, value: @school.id) %>

    <p>Här lägger du till en rektor till <strong><%= @school.name %></p></strong>

<div class="row">
  <div class="large-12 columns">
    <table class="auto_size">
      <thead>
      <tr>
        <th>Lägg till</th>
        <th>Namn</th>
        <th>Email</th>
        <th>Yrke</th>

      </tr>
      </thead>
      <tbody>

      <% @users.each do |p| %>
        <% if @users.where(:id).empty? %>
          <% @showPrincipal.push(p) %>
          <% @temp = SchoolUser.where(:user_id == p.id) %>
          <% @temp.each do |ap| %>
            <% if ap.school_id == @school.id %>
              <% @hidePrincipal.push(ap)%>
            <% end %>
            <% @showPrincipal.each do |x| %>
              <% @hidePrincipal.each do |y| %>
                <% if x.id === y.user_id %>
                  <% @showPrincipal.delete(x) %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>



      <% @showPrincipal.each do |t| %>
        <tr>
          <td><%= f.radio_button :user_id, t.id%></td>
          <td><%= t.name %></td>
          <td><%= t.email %></td>
          <td><%= t.user_type %></td>
        </tr>
      <% end %>

      

      </tbody>
    </table>
  </div>
</div>

    <%= f.submit "Lägg till rektor", :class => "button tiny", style: 'margin-top: 20px; float: left; margin-right: 10px;' %>
<% end %>


app/views/schools/_addTeacherForm.html.erb
<%= form_for SchoolUser.new do |f| %>
    <%= f.hidden_field(:school_id, value: @school.id) %>

    <div class="row">
      <div class="large-12 columns">
        <table class="auto_size">
          <thead>
          <tr>
            <th>Lägg till</th>
            <th>Namn</th>
            <th>Email</th>
            <th>Yrke</th>

          </tr>
          </thead>
          <tbody>

          <% @teachers.each do |p| %>
            <% if @teachers.where(:id).empty? %>
              <% @showTeacher.push(p) %>
              <% @temp = SchoolUser.where(:user_id == p.id) %>
              <% @temp.each do |ap| %>
                <% if ap.school_id == @school.id %>
                  <% @hideTeacher.push(ap)%>
                <% end %>
                <% @showTeacher.each do |x| %>
                  <% @hideTeacher.each do |y| %>
                    <% if x.id === y.user_id %>
                      <% @showTeacher.delete(x) %>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>


          <% @showTeacher.each do |t| %>
              <tr>
                <td><%= f.radio_button :user_id, t.id %></td>
                <td><%= t.name %></td>
                <td><%= t.email %></td>
                <td><%= t.user_type %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <%= f.submit "Registrera personal", :class => "button tiny", style: 'margin-top: 20px; float: left; margin-right: 10px;' %>
<% end %>

app/views/schools/_formEdit.html.erb
<%= form_for(@school, :html => {:multipart => true}) do |f| %>
    <% if @school.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@school.errors.count, 'fel') %> hindrar denna användaren från att sparas:</h2>
          <ul>
            <% @school.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
      <h3>Editera en skola</h3>
      <h4 class="subheader">Här kan du editera en redan befintlig skola.</h4>
      <br />
      <div class="field">
        <%= f.label :name, 'Lägg till en ny skola' %>
        <%= f.text_field :name, :required => true %>
      </div>
      <div class="field">
        <%= f.label :district, 'I vilket län ligger skolan?' %>
        <%= f.select(:district, [['Blekinge'], ['Dalarnas'], ['Gotlands'], ['Gävleborgs'], ['Hallands'], ['Jämtlands'], ['Jönköpings'], ['Kalmar'], ['Kronobergs'], ['Norrbottens'], ['Skåne'], ['Dalarnas'], ['Stockholms'], ['Södermanslands'], ['Uppsala'], ['Värmlands'], ['Västerbottens'], ['Västernorrlands'], ['Västmanlands'], ['Västra Götalands'], ['Örebro'], ['Östergötlands']]) %>
      </div>
      <div class="field">
        <%= f.label :file, 'Välj en bild att ha i mitten av hjulet' %><br>
        <%= image_tag @school.file.url, :class => 'centerImage' if @school.file? %>

        <%= f.file_field :file, :class => 'centerImageFileField', accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
        <% if @school.file? %>
          <p>
            <%= f.check_box :remove_file %>
            <%= f.label :remove_file, 'Ta bort bild' %>
          </p>
        <% end %>
      </div>
      <div id="delete_file" >
        <% if @school.file.present? %>
        <% end %>
      </div>
      <div class="field">
        <%= f.submit 'Uppdatera', :class => 'button tiny' %>
        <%= link_to 'Tillbaka', schools_path, class: 'button tiny back', style: 'color: white' %>
      </div>
<% end %>

app/views/schools/_formNew.html.erb
<%= form_for(@school, :html => {:multipart => true}) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, 'fel') %> hindrar denna användaren från att sparas:</h2>
      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      <h3>Lägg till en ny skola</h3>
      <h4 class="subheader">Här kan du lägga till en ny skola genom att ange namn på skolan, och vilket län den ligger i.</h4>
  <br />
  <div class="field">
    <%= f.label :name, 'Lägg till en ny skola' %>
    <%= f.text_field :name, :required => true %>
  </div>
  <div class="field">
     <%= f.label :district, 'I vilket län ligger skolan?' %>
     <%= f.select(:district, [['Blekinge'], ['Dalarnas'], ['Gotlands'], ['Gävleborgs'], ['Hallands'], ['Jämtlands'], ['Jönköpings'], ['Kalmar'], ['Kronobergs'], ['Norrbottens'], ['Skåne'], ['Dalarnas'], ['Stockholms'], ['Södermanslands'], ['Uppsala'], ['Värmlands'], ['Västerbottens'], ['Västernorrlands'], ['Västmanlands'], ['Västra Götalands'], ['Örebro'], ['Östergötlands']]) %>
  </div>
  <div class="field">
    <%= f.label :file, 'Välj en bild att ha i mitten av hjulet' %><br>
    <%= f.file_field :file, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
  </div>
  <div class="field">
    <%= f.submit 'Lägg till', :class => 'button tiny' %>
    <%= link_to 'Tillbaka', schools_path, class: 'button tiny back', style: 'color: white' %>
  </div>
<% end %>

app/views/schools/add_principal.html.erb
<h1>Lägg till rektor</h1>
<%= render 'addPrincipalForm' %>
<%= link_to "Tillbaka", (:back), class: 'button tiny back', style: 'color: white; margin-top: 20px;' %>

app/views/schools/add_teacher.html.erb
<h1>Lägg till personal</h1>
<%= render 'addTeacherForm' %>
<%= link_to "Tillbaka", (:back), class: 'button tiny back', style: 'color: white; margin-top: 20px;' %>

app/views/schools/destroy.js.erb
console.log("#asset_<%= @asset_id %>");


$("#asset_<%= @asset_id %>").hide("slow");

app/views/schools/edit.html.erb
<%= render 'formEdit' %>


app/views/schools/index.html.erb
<br />
<h4>Lista över skolor</h4>
<div class="field">
<table>
  <thead>
    <tr>
      <th>Skolor</th>
      <th class="list">Lägg till personal</th>
      <th class="list">Redigera</th>
      <th class="list">Ta bort</th>
    </tr>
  </thead>

  <tbody>
   
    <% @schools.each do |school| %>
      <%if current_user.user_type=="principal" %>
        <% current_user.schools.map do |yourSchools| %>
          <% if yourSchools.id == school.id %>
                  <tr class="user" id="asset_<%= school.id %>">
                    <td><%= school.name %>  (<%= school.district %> län)</td>
                    <td><%= link_to 'Lägg till personal', school %></td>
                    <td></td>
                    <td></td>
                  </tr>
          <%end %>
        <%end%>

      <% elsif current_user.user_type=="admin" %>
          <tr class="user" id="asset_<%= school.id %>">
            <td><%= school.name %>  (<%= school.district %> län)</td>
            <td><%= link_to 'Lägg till personal', school %></td>
            <td><%= link_to 'Redigera', edit_school_path(school) %></td>
            <td> <%= link_to 'Ta bort', school_path(school) , method: :delete,
                             data: {confirm: "Är du säker på att du vill ta bort skolan?"}, remote: true %> <br/>
            </td>
          </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>
<br>
<% if current_user.user_type == "admin" %>
  <%= link_to 'Lägg till skola', new_school_path, class: 'button tiny', style: 'color: white; margin-top: 20px;' %>
<% end %>

app/views/schools/new.html.erb
<%= render 'formNew' %>

app/views/schools/show.html.erb
<% if @noticeE == 2 %>
<p id="noticeerror"><%= notice %></p>
<% else %>
<p id="notice"><%= notice %></p>
<% end %>

<div class="row">
    <div class="large-12 columns">
      <p></p>
      <h2>Personal på <strong><%= @school.name %></strong> - <%= @school.district %></h2>
    </div>
</div>
<div class="row">
  <div class="large-12 columns">
        <h4 class="subheader">Sök på en person eller en epostadress</h4>
  </div>
</div>
  <div class="row">
    <div class="large-12 columns">
          <table>
          <thead>
          <tr>
            <th>Rektor</th>
            <th>E-post</th>
            <th class="list">Registrerad</th>
            <th class="list">Ta bort</th>
          </tr>
          </thead>
          <tbody>
          <% @activePrincipals.each do |ap| %>
              <% if ap.school_id == @school.id %>
                  <% @principals.each do |p| %>
                      <% if p.id == ap.user_id %>
                          <tr>
                            <td><%= p.name %></td>
                            <td><%= p.email %></td>
                            <td><%= (ap.updated_at).to_s[0, 11] %></td>
                            <td><%= link_to 'Avregistrera', ap, method: :delete, data: { confirm: 'Är du säker på att du vill avregistera ' + p.name} %></td>
                          </tr>
                      <% end %>
                  <% end %>
              <% end %>
          <% end %>
          </tbody>
        </table>
      <br/>
       <p><%= link_to 'Registera rektor på skolan', school_add_principal_path(@school), :class => 'button tiny', style: 'color: white; margin-top: 20px;' %></p>
    </div>
 </div>
  <div class="row">
  <div id="second" class="large-12 columns">
      <table>
      <thead>
      <tr>
        <th>Personal</th>
        <th>E-post</th>
        <th class="list">Registrerad</th>
        <th class="list">Ta bort</th>
      </tr>
      </thead>
      <tbody>
      <% @activeTeachers.each do |at| %>
          <% if at.school_id == @school.id %>
              <% @teachers.each do |t| %>
                  <% if t.id == at.user_id %>
                      <tr>
                        <td><%= t.name %></td>
                        <td><%= t.email %></td>
                        <td><%= (at.updated_at).to_s[0, 11] %></td>
                        <td><%= link_to 'Avregistrera', at, method: :delete, data: { confirm: 'Är du säker på att du vill avregistera ' + t.name } %></td>
                      </tr>
                  <% end %>
              <% end %>
          <% end %>
      <% end %>
      </tbody>
    </table>
    <br/>

      <p><%= link_to 'Registera personal på skolan', school_add_teacher_path(@school), :class => 'button tiny', style: 'color: white; margin-top: 20px;' %></p>

  </div>
</div>
<% if current_user.user_type == "admin" %>
  <%= link_to 'Redigera skolan', edit_school_path(@school), class: 'button tiny', style: 'color: white; margin-top: 20px; margin-right: 5px;' %>
<% end %>
<%= link_to 'Tillbaka', schools_path, class: 'button tiny back' %>

