config/routes.rb
Kvalitetshjulet::Application.routes.draw do

  get "user_workgroups/create"
  get "user_workgroups/destroy"
  get "active_teachers/new"
  get "active_teachers/destroy"
  get "active_principals/new"
  get "schools_users/new"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]
  get "sessions", to: "sessions#index"

  resources :active_principals
  resources :high_lights
  resources :school_users
  resources :active_teachers
  resources :events
  resources :event_types, :path => "event-types"
  get '/event-types/remove/:id', :to => 'event_types#remove', :as => :remove_event_type
  resources :schools do
    resources :schools_users
    resources :active_principals
    resources :active_teachers
    get 'add' => 'schools_users#new'
    get 'add_teacher' => 'schools#add_teacher'
    get 'add_principal' => 'schools#add_principal'
    get 'destroy_image' => 'schools#destroy_image'

    scope '/principal', :module => 'principal', :as => 'principal' do
      resources :users
    end
    scope '/teacher', :module => 'teacher', :as => 'teacher' do
      resources :users
      get 'schools' => 'users#school'
    end
  end

  resources :user_workgroups

  resources :workgroups do
    get 'add_user' => 'workgroups#add_user'
  end

  get '/users/:id', :to => 'users#show', :as => :user

  scope '/admin', :module => 'admin', :as => 'admin' do
      resources :users
  end

  scope '/juror', :module => 'juror', :as => 'juror' do
      resources :users
  end

  scope '/principal', :module => 'principal', :as => 'principal' do
      resources :users
  end

  scope '/teacher', :module => 'teacher', :as => 'teacher' do
      resources :users do
        collection { post :import }
      get 'schools' => 'users#school'
    end
  end

  get "sessions/test", to: "sessions#test"
  get "sessions/events", to: "sessions#events"
  get "sessions/show_week_events/:id/:type", to: "sessions#show_week_events"
  get "sessions/edit_week_event/:id(/:type)", to: "sessions#edit_week_event"
  get "sessions/new_week_event/:id/:type", to: "sessions#new_week_event"
  get "sessions/user/:id", to: "sessions#user"
  get "sessions/changeyear/:year", to: "sessions#set_selected_year"

  get "sessions/show_high_lights/:id", to: "sessions#show_high_lights"
  get "sessions/new_high_lights/:id", to: "sessions#new_high_lights"
  get "sessions/edit_high_lights/:id", to: "sessions#edit_high_lights"
  get "sessions/show_specific_highlights/:id", to: "sessions#show_specific_highlights"

  get "sessions/delete_file/:id", to: "sessions#delete_file"

  root 'sessions#index'










end

app/controllers/event_types_controller.rb
class EventTypesController < ApplicationController
  before_action :auth
  before_action :set_event_type, only: [:show, :edit, :update, :remove, :destroy]

  # GET /event_types
  # GET /event_types.json
  def index
    @event_types = EventType.all
  end

  # GET /event_types/1
  # GET /event_types/1.json
  def show
  end

  # GET /event_types/new
  def new
    @event_type = EventType.new
  end

  # GET /event_types/1/edit
  def edit
  end

  # POST /event_types
  # POST /event_types.json
  def create
    @event_type = EventType.new(event_type_params)

    respond_to do |format|
      if @event_type.save
        format.html { redirect_to event_types_url }
        format.json { render action: 'new', status: :created, location: @event_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @event_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_types/1
  # PATCH/PUT /event_types/1.json
  def update
    respond_to do |format|
      if @event_type.update(event_type_params)
        format.html { redirect_to event_types_url }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove
    if EventType.count < 2
      redirect_to event_types_url, notice: "Det måste alltid finnas minst en aktivitetstyp" and return
    end

    @other_event_types = EventType.where.not(id: params[:id])
  end

  # DELETE /event_types/1
  # DELETE /event_types/1.json
  def destroy
    begin
      if params.has_key?(:event)
        @event_type.events.update_all(type_id: params[:event][:type_id])
      end

      if !@event_type.events.count.zero?
        redirect_to remove_event_type_url and return
      else
        @event_type.destroy        
      end
    rescue StandardError => e
      flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to event_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_type
      @event_type = EventType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_type_params
      params.require(:event_type).permit(:name, :color)
    end

    def auth      
      if session[:user_id] == nil
        redirect_to root_url, notice: "Du måste logga in med ditt google konto för att använda applikationen."
      elsif session[:user_type] != "admin"
        redirect_to root_url, notice: "Du har inte de nödvändiga rättigheterna för att kunna använda den delen av applikationen."
      end
    end
end

app/helpers/event_types_helper.rb
module EventTypesHelper
end

app/views/event_types/_form.html.erb
<%= form_for(@event_type) do |f| %>
  <% if @event_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_type.errors.count, "error") %> prohibited this event_type from being saved:</h2>

      <ul>
      <% @event_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Namn' %><br>
    <%= f.text_field :name, :required => true %>
  </div>
  <div class="field color-picker">
    <%= f.label :color, 'Färg' %><br>
    <%= f.text_field :color, :required => true, :data => {:type => 'color-picker'} %>
  </div>

  <div class="actions">
    <%= f.submit 'Spara', class: 'button tiny left' %>
  </div>
<% end %>

app/views/event_types/edit.html.erb
<h1>Ändra Aktivitetstyp</h1>

<%= render 'form' %>

<%= link_to 'Avbryt', event_types_path, class: 'button tiny back right', style: 'color: white' %>

app/views/event_types/index.html.erb
<h1>Aktivitetstyper</h1>

<div id="notices">
    <% flash.each do |name, msg| -%>
        <div class="<%= name %>">
            <%= msg %>
            <button class="close-notice" onclick="hideThis(this);">x</button>
        </div>
    <% end -%>
</div>

<div class="row">
  <% @event_types.each do |event_type| %>
  <div class="large-3 medium-4 small-6 tiny-12 columns event-type-box">
    <div class="panel">
      <h3 class="text-center"><%= event_type.name %></h3>
      <div class="row spacing">
        <div class="color-box" data-color="<%= event_type.color %>"></div>
      </div>
      <div class="bottom">
        <%= link_to 'Ändra', edit_event_type_path(event_type), class: "button tiny"  %>
        <%= link_to 'Ta bort', event_type, method: :delete, class: "button alert tiny right", data: { confirm: 'Är du säker på att du vill ta bort Aktivitetstypen?' } %>
        <!-- <%= link_to 'Ta bort', remove_event_type_path(event_type), class: "button alert tiny right", data: { confirm: 'Är du säker på att du vill ta bort Aktivitetstypen?' } %> -->
      </div>
    </div>
  </div>
  <% end %>

  <%= link_to new_event_type_path, class: 'large-2 medium-4 small-6 tiny-12 columns left add-event-type' do %>
    <div class="panel"><div class="text-center add-icon fi-plus"></div></div>
  <% end %>
</div>
  
<br>

<%= link_to '< Tillbaka till Hjulet', sessions_path  %>

app/views/event_types/new.html.erb
<h1>Ny Aktivitetstyp</h1>

<%= render 'form' %>

<%= link_to 'Avbryt', event_types_path, class: 'button tiny back right', style: 'color: white' %>

app/views/event_types/remove.html.erb
<h1>Ta bort <b><%= @event_type.name %></b> - Aktivitetstyp</h1>
<h2></h2>
<%= form_for(@event_type, method: :delete) do %>
  <% if @event_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= @event_type.errors.count %> fel stoppade aktivitetstypen från att sparas:</h2>

      <ul>
      <% @event_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="remove-form field row">
    <div class="large-8 medium-10 small-12 columns">
      <h3>Det finns <%= @event_type.events.count %> aktivitet<%= 'er' if @event_type.events.count != 1 %> som är av denna typ.</h3>
      <table data-escape="dataTable">
        <thead>
          <tr>
            <th>Titel</th>
            <th>Senast ändrad</th>
            <th>Kommentar</th>
          </tr>
        </thead>
        <tbody>
        <% @event_type.events.each do |e| %>
          <tr>
            <td><%= e.title %></td>
            <td><%= e.updated_at.strftime('%b %d, %Y') %></td>
            <td><%= truncate(strip_tags(e.comment)) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="remove-form row">
    <div class="field large-8 medium-10 small-12 columns">
      <%= label_tag :event, 'Ändra samtliga aktiviteters typ till:' %><br>
      <%= collection_select(:event, :type_id, @other_event_types, :id, :name, :required => true ) %>
    </div>
  </div>


  <div class="remove-form row">
    <div class="actions large-8 medium-10 small-12 columns">
      <%= link_to 'Avbryt', event_types_path, class: 'button tiny warn left' %> <%= submit_tag 'Ta bort Aktivitetstypen', class: 'button tiny right' %> 
    </div>
  </div>


<% end %>

app/views/event_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event_type.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @event_type.color %>
</p>

<%= link_to 'Edit', edit_event_type_path(@event_type) %> |
<%= link_to 'Back', event_types_path %>